{ config, lib, ... }:
let
  colors = config.lib.stylix.colors.withHashtag;
in
{
  options.stylix.targets.ghostty.enable = config.lib.stylix.mkEnableTarget "ghostty" false;

  config = lib.mkIf (config.stylix.enable && config.stylix.targets.ghostty.enable) {
    programs.ghostty.colorSchemes.stylix = with colors; {
      background-opacity = config.stylix.opacity.terminal;
      polarity = config.stylix.polarity;
      background = base00;
      foreground = base05;
      cursor-color = base05;
      selection_bg = base02;
      selection_fg = base00;
      pallete0 = base00;
      pallete1 = base08;
      pallete2 = base0B;
      pallete3 = base0A;
      pallete4 = base0D;
      pallete5 = base0E;
      pallete6 = base0C;
      pallete7 = base05;
      pallete8 = base03;
      pallete9 = base08;
      pallete10 = base0B;
      pallete11 = base0A;
      pallete12 = base0D;
      pallete13 = base0E;
      pallete14 = base0C;
      pallete15 = base07;
      pallete16 = base09;
      pallete17 = base0F;
      pallete18 = base01;
      pallete19 = base02;
      pallete20 = base04;
      pallete21 = base06;
    };

    xdg.configFile.".config/ghostty/config".text =
      with colors;
      with config.stylix.fonts;
      lib.mkForce ''
        -- Generated by stylix
        font-family = "${monospace.name}"
        font-size = ${sizes.terminal}
        background-opacity = ${background-opacity}
        polarity = "${polarity}"

        background = ${base00}
        foreground = ${base05}
        cursor-color = ${cursor-color}

        selection_bg = ${base02}
        selection_fg = ${base00}

        palette = 0=${base00}
        palette = 8=${base08}
        palette = 1=${base01}
        palette = 9=${base09}
        palette = 2=${base02}
        palette = 10=${base0A}
        palette = 3=${base03}
        palette = 11=${base0B}
        palette = 4=${base04}
        palette = 12=${base0C}
        palette = 5=${base05}
        palette = 13=${base0D}
        palette = 6=${base06}
        palette = 14=${base0E}
        palette = 7=${base07}
        palette = 15=${base0F}
      '';
  };
}
